language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script: "mvn clean install"

branches:
  only:
    - develop
    
#after_success:
#  - mvn clean cobertura:cobertura-integration-test coveralls:report
