language: java

jdk:
  - oraclejdk8
  - openjdk7

branches:
  only:
    - develop

script: mvn clean test -Pjacoco -Dsaturn.it.log.level=WARN -DargLine="-Xmx2048m -Xms1024m -XX:MaxPermSize=512m -XX:-UseGCOverheadLimit"
